# Generated by Django 4.1 on 2022-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=100)),
                ('velocidade_maxima', models.IntegerField()),
                ('data_lancamento', models.DateField()),
            ],
        ),
    ]
